apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      name: postgresdb
      namespace: voting-app
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres:15-alpine
        envFrom:
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 