apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      name: result
      namespace: voting-app
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: jojogojo/result-image
        ports:
        - containerPort: 80
          name: result