apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      name: vote
      namespace: voting-app
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: jojogojo/vote-image
        ports:
        - containerPort: 80
          name: vote